name: SKY LAB - FORMS Backend CI Pipeline (GHCR)

on:
  push:
    tags: [ "v*.*.*" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: ./src
          push: true
          tags: |
            ghcr.io/skylab-kulubu/forms-backend:latest
            ghcr.io/skylab-kulubu/forms-backend:${{ github.sha }}
            ghcr.io/skylab-kulubu/forms-backend:${{ github.ref_name }}
